### ISSUE TITLE
code will not show highlighting in preview mode

### ISSUE THREAD

**Issue by mylovesaber** [nothingislost/obsidian-codemirror-options#90]
version:0.9.0
If I enable "Use CodeMirror for syntax highlighting in preview mode", all the code highlighting will have no effect. I just want to show the line number.
Is it a bug?

**Comment by nothingislost** [comment]
I believe this should be fixed in the new 0.9.1 release

**Comment by mylovesaber** [comment]
> I believe this should be fixed in the new 0.9.1 release

One more bug and a not fixed bug.
1. If I don't specify the language name, the preview code is too hard to watch(This happened in the previous and the latest version)
![image](https://user-images.githubusercontent.com/36480362/142657535-522f05ae-a28d-45ec-915e-408abd40c19e.png)

2. The bug is still be there. 
![image](https://user-images.githubusercontent.com/36480362/142657660-31a69e60-23b1-4fa9-8a78-6128b06c293f.png)

**Comment by mylovesaber** [comment]
> I believe this should be fixed in the new 0.9.1 release
Maybe another bug? If I combine codemirror with admonition, the symbols are hard to see clearly in preview mode.
![image](https://user-images.githubusercontent.com/36480362/142733793-4ec41eb7-2e56-4089-9289-739398714232.png)

**Comment by nothingislost** [comment]
I'll look into these but the nested code blocks inside of admonitions is going to be a bit tricky to sort out. You're seeing different highlighting because that's Prism.JS highlighting the code on the right side vs. CodeMirror. I'll see what I can do.
